<?php

function image_menus_menu()
{
	
	//------------------------  MAIN MENU ----------------------------------- 
	// Products 
	$items['products'] = array(		'title'				=> 'Products',
									'description' 		=> 'Products',
									'weight'			=> 1,
									'menu_name'			=> 'main-menu',
									'page callback' 	=> '_image_menus_basic',
									'access callback' 	=> TRUE,	
									'expanded' 			=> TRUE,
								);
	// News 
	$items['news'] = array(			'title'				=> 'News',
									'description' 		=> 'Image news and general information',
									'weight'			=> 2,
									'menu_name'			=> 'main-menu',
									'page callback' 	=> '_image_menus_basic',
									'access callback' 	=> TRUE,	
									'expanded' 			=> TRUE,
								);
	// Downloads 
	$items['downloads'] = array(	'title'				=> 'Downloads',
									'description' 		=> 'Downloads',
									'weight'			=> 8,
									'menu_name'			=> 'main-menu',
									'page callback' 	=> '_image_menus_basic',
									'access callback' 	=> TRUE,	
									'expanded' 			=> TRUE,
								);							
	// About 
	$items['about'] = array(		'title'				=> 'About Us',
									'description' 		=> 'About Us',
									'weight'			=> 5,
									'menu_name'			=> 'main-menu',
									'page callback' 	=> '_image_menus_basic',
									'access callback' 	=> TRUE,	
									'expanded' 			=> TRUE,
								);						
	// Legal 
	$items['legal'] = array(		'title'				=> 'Legal Notice',
									'description' 		=> 'Legal Notice',
									'weight'			=> 9,
									'menu_name'			=> 'menu-information',
									'page callback' 	=> '_image_menus_basic',
									'access callback' 	=> TRUE,	
									'expanded' 			=> TRUE,
								);
								
	return $items;
}

/**
 * Page callback for the simplest introduction menu entry.
 *
 * @param $content
 *   Some content passed in.
 */
function _image_menus_basic ($content = NULL) {
  return '<div>' . $content . '</div>';
}