<?php

function image_menus_menu()
{
	
	//------------------------  MAIN MENU ----------------------------------- 
	//News & Voices	
	$items['&#35;block-views-about-block'] = array(	'title'				=> 'About Us',
												'description' 		=> 'About Us',
												'weight'			=> 5,
												'menu_name'			=> 'main-menu',
												'page callback' 	=> '_image_menus_menu_page',
												'access callback' 	=> TRUE,	
												'expanded' 			=> TRUE,
											);
								
	return $items;
}

/**
 * Page callback for use with most of the menu entries. The arguments it
 * receives determine what it outputs.
 *
 * @param $content
 *   The base content to output.
 * @param $arg1
 *   First additional argument from the path used to access the menu
 * @param $arg2
 *   Second additional argument.
 */
function _image_menus_menu_page($content = NULL, $arg1 = NULL, $arg2 = NULL) {
	// We don't want any output here
  	return '';
}