<?php

/**
 * This is example code for a Drupal 6 to Drupal 7 migration. This won't actually
 * work without defining the referenced vocabularies, content types, and fields
 * on each side.
 */

/**
 * Implements hook_flush_caches().
 */
function migrate_d2d_image_flush_caches() {
  migrate_d2d_image_register_migrations();
}

/**
 * Register all D6->D7 migrations.
 */
function migrate_d2d_image_register_migrations() {
	/**
	 * Each migration being registered takes an array of arguments, some required
	 * and some optional. Start with the common arguments required by all - the
	 * source_connection (connection key, set up in settings.php, pointing to
	 * the Drupal 6 database) and source_version (major version of Drupal).
	 */
	$common_arguments = array(
	  'source_connection' => 'legacy',
	  'source_version' => 6,
	);

	//Roles migration
	$role_arguments = $common_arguments + array(
	  'machine_name' => 'Roles',
	  'description' => t('Import Drupal 6 roles'),
	  'role_mappings' => array(
	    'Editor' => 'Editor',
	  ),
	);	
	Migration::registerMigration('DrupalRole6Migration', 
	  $role_arguments['machine_name'], $role_arguments);

	//User migration
	// The description and the migration machine name are also required arguments,
	// which will be unique for each migration you register.
	$arguments = $common_arguments + array(
	  'description' => t('Migration of users from Drupal 6'),
	  'machine_name' => 'User',
	);
	// We just use the migrate_d2d D6 migration class as-is.
	Migration::registerMigration('DrupalUser6Migration', $arguments['machine_name'],
	                             $arguments);	
	
	//Files migration
	$file_arguments = $common_arguments + array(
	  'machine_name' => 'Files',
	  'description' => t('Import Drupal 6 files'),
	  'user_migration' => 'User',
	  'default_uid' => 1,
	  'source_dir' => '../imageservice_local_drupal6/sites/default/files',
	  'destination_dir' => 'public://',
	);
	Migration::registerMigration('DrupalFile6Migration', 
	  $file_arguments['machine_name'], $file_arguments);

  // For vocabulary migrations, source_vocabulary and destination_vocabulary are
  // required arguments. Note that in Drupal 6 vocabularies did not have machine
  // names, so we use the vocabulary ID to uniquely identify them.
  $vocabulary_arguments = array(
    array(
      'description' => t('Migration of Grape Varieties terms from Drupal 6'),
      'machine_name' => 'Grape_Varieties',
      'source_vocabulary' => '4',  // D6 Vocabulary ID
      'destination_vocabulary' => 'grape_varieties',
    ),
    array(
      'description' => t('Migration of Menu terms from Drupal 6'),
      'machine_name' => 'Menu',
      'source_vocabulary' => '5',  // D6 Vocabulary ID
      'destination_vocabulary' => 'menu',
    ),
    array(
      'description' => t('Migration of Features terms from Drupal 6'),
      'machine_name' => 'Features',
      'source_vocabulary' => '8',  // D6 Vocabulary ID
      'destination_vocabulary' => 'features',
    ),
    array(
      'description' => t('Migration of Products Categories terms from Drupal 6'),
      'machine_name' => 'Products_Categories',
      'source_vocabulary' => '9',  // D6 Vocabulary ID
      'destination_vocabulary' => 'products_categories',
    ),
    array(
      'description' => t('Migration of Supplier Name terms from Drupal 6'), 
      'machine_name' => 'Supplier_Names',
      'source_vocabulary' => '9',  // D6 Vocabulary ID
      'destination_vocabulary' => 'supplier_names',
    ),
  );

  // Again, we're using the migrate_d2d class directly.
  // The soft dependency says that while we don't have to run the user migration
  // first, we want to make sure it's listed first so the vocubularies are
  // listed right ahead of the node migrations.
  $common_vocabulary_arguments = $common_arguments + array(
    'class_name' => 'DrupalTerm6Migration',
    'soft_dependencies' => array('User'),
  );
  foreach ($vocabulary_arguments as $arguments) {
    $arguments += $common_vocabulary_arguments;
    Migration::registerMigration($arguments['class_name'], $arguments['machine_name'],
                                 $arguments);
  }

  // Node migrations - each has its own class derived from the migrate_d2d class,
  // specifying its particular field mappings and transformations. source_type
  // and destination_type are required arguments.
  $node_arguments = array(
	  array(
	    'class_name' => 'CatchphraseMigration',
	    'description' => t('Migration of Catchphrase nodes from Drupal 6'),
	    'machine_name' => 'Catchphrase',
	    'source_type' => 'catchphrase',
	    'destination_type' => 'catchphrase',
		'dependencies' => array('User'),
	  ),	
	  array(
	    'class_name' => 'CountryMigration',
	    'description' => t('Migration of Catchphrase nodes from Drupal 6'),
	    'machine_name' => 'Country',
	    'source_type' => 'country',
	    'destination_type' => 'country',
		'dependencies' => array('Files'),
	  ),
	  array(
	    'class_name' => 'DownloadItemMigration',
	    'description' => t('Migration of Downloadable Items nodes from Drupal 6'),
	    'machine_name' => 'DownloadItem',
	    'source_type' => 'download_item',
	    'destination_type' => 'download_item',
		'dependencies' => array('Files'),
	  ),
	  array(
	    'class_name' => 'FaqMigration',
	    'description' => t('Migration of Frquently Asked Questions nodes from Drupal 6'),
	    'machine_name' => 'Faq',
	    'source_type' => 'faq',
	    'destination_type' => 'faq',
	  ),
	  array(
	    'class_name' => 'GalleryMigration',
	    'description' => t('Migration of Gallery nodes from Drupal 6'),
	    'machine_name' => 'Gallery',
	    'source_type' => 'gallery',
	    'destination_type' => 'gallery',
		'dependencies' => array('Files'),
	  ),
	  array(
	    'class_name' => 'HeaderMigration',
	    'description' => t('Migration of Header nodes from Drupal 6'),
	    'machine_name' => 'Header',
	    'source_type' => 'header',
	    'destination_type' => 'header',
		'dependencies' => array('Files'),
	  ),
	  array(
	    'class_name' => 'ImageDetailMigration',
	    'description' => t('Migration of Image Detail nodes from Drupal 6'),
	    'machine_name' => 'ImageDetail',
	    'source_type' => 'image_detail',
	    'destination_type' => 'image_detail',
		'dependencies' => array('Files'),
	  ),
	  array(
	    'class_name' => 'NewsMigration',
	    'description' => t('Migration of News nodes from Drupal 6'),
	    'machine_name' => 'News',
	    'source_type' => 'news',
	    'destination_type' => 'news',
		'dependencies' => array('Files' , 'User'),
	  ),
	  array(
	    'class_name' => 'WineProductMigration',
	    'description' => t('Migration of Wine nodes from Drupal 6'),
	    'machine_name' => 'WineProduct',
	    'source_type' => 'wine',
	    'destination_type' => 'product',
		'dependencies' => array('Files' , 'User', 'Grape_Varieties' , 'Features', 'Country', 'Supplier' ),
	  ),
	  array(
	    'class_name' => 'OliveOilProductMigration',
	    'description' => t('Migration of OliveOil nodes from Drupal 6'),
	    'machine_name' => 'OliveOil',
	    'source_type' => 'olive_oil',
	    'destination_type' => 'product',
		'dependencies' => array('Files' , 'User', 'Products_Categories' , 'Features', 'Country', 'Supplier' ),
	  ),
		  array(
		    'class_name' => 'WineItemMigration',
		    'description' => t('Migration of Wine nodes from Drupal 6'),
		    'machine_name' => 'WineItem',
		    'source_type' => 'wine',
		    'destination_type' => 'item',
			'dependencies' => array('Files' , 'User', 'Grape_Varieties' , 'Features', 'Country', 'Supplier' ),
		  ),
		  array(
		    'class_name' => 'OliveOilItemMigration',
		    'description' => t('Migration of OliveOil nodes from Drupal 6'),
		    'machine_name' => 'OliveOilItem',
		    'source_type' => 'olive_oil',
		    'destination_type' => 'item',
			'dependencies' => array('Files' , 'User', 'Products_Categories' , 'Features', 'Country', 'Supplier' ),
		  ),
	  array(
	    'class_name' => 'SupplierMigration',
	    'description' => t('Migration of Supplier nodes from Drupal 6'),
	    'machine_name' => 'Supplier',
	    'source_type' => 'supplier',
	    'destination_type' => 'supplier',
		'dependencies' => array('Files' , 'User', 'Country'),
	  ),	
  );

  // Tell the node migrations where the users are coming from, so they can
  // set up the dependency and resolve D6->D7 uids.
  $common_node_arguments = $common_arguments + array(
    'user_migration' => 'User',
  );
  foreach ($node_arguments as $arguments) {
    $arguments = array_merge_recursive($arguments, $common_node_arguments);
    Migration::registerMigration($arguments['class_name'], $arguments['machine_name'],
                                 $arguments);
  }

  // Menu migrations -- same requirements as users
  $menu_arguments = $common_arguments + array(
    'description' => t('Migration of menus from Drupal 6'),
    'machine_name' => 'Menu',
  );

  // We just use the migrate_d2d D6 migration class as-is.
  Migration::registerMigration('DrupalMenu6Migration', $menu_arguments['machine_name'],
                               $menu_arguments);

  // Menu links migrations -- basic requirements, plus must set up menu dependency
  $menu_links_arguments = $common_arguments + array(
    'description' => t('Migration of menu links from Drupal 6'),
    'machine_name' => 'MenuLinks',
    'menu_migration' => $menu_arguments['machine_name'],
  );
  Migration::registerMigration('DrupalMenuLinks6Migration', $menu_links_arguments['machine_name'],
                               $menu_links_arguments);
}

/**
 * Implements hook_migrate_api().
 */
function migrate_d2d_image_migrate_api() {
  $api = array(
    'api' => 2,
  );
  return $api;
}
