<?php

// Fixes the translation problem in Views Exposed Form
function image_service_form_alter(&$form, &$form_state, $form_id)
{
	global $language;
	
	// Only do this if the page is not in English
	if($language->language != 'en'){
		if($form_id == 'views_exposed_form'){
			foreach( $form['field_country_tid']['#options'] as $key=>$value){
				if($key != 'All'){
					$term = taxonomy_term_load($key);
					if (module_exists('i18n_taxonomy')) {
					    module_load_include('inc', 'i18n', 'i18n_taxonomy.pages');
					    $term = i18n_taxonomy_localize_terms($term);
						$form['field_country_tid']['#options'][$key] = $term->name;
					}
				}
			}
		}
	}
	
	if($form_id == 'views_exposed_form'){
		$form['submit']['#attributes']['class'][] = 'btn-inverse btn';
	}
}



function image_service_preprocess_page(&$variables)
{
	// SITEWIDE
	if(empty($variables['catchphrases']))
	{
		$variables['catchphrases'] = _image_service_render_block(block_load('views', 'catchphrases-block'), '<none>');
	}
	
	if(empty($variables['grapepickers'])){
		$variables['grapepickers'] = _image_service_render_block( block_load('views', 'illustrations-block') , '<none>');
	}
	
	//Search form
	if(empty($variables['search_box'])){
		$search_box = drupal_get_form('search_form');
		$variables['search_box'] = drupal_render($search_box);
	}

	//Suppliers Menu
	if(empty($variables['suppliers-menu'])){
		$suppliers_menu = block_load('menu', 'menu-suppliers');
		$variables['suppliers-menu'] = _image_service_render_block($suppliers_menu, $suppliers_menu->title  );
	}

	//Countries Menu
	if(empty($variables['countries-menu'])){
		$countries_menu = block_load('menu', 'menu-countries');   
		$variables['countries-menu'] =  _image_service_render_block($countries_menu, $countries_menu->title  );
	}

	//Products Menu
	if(empty($variables['products-menu'])){
		$products_menu =  block_load('menu', 'menu-products');   
		$variables['products-menu'] = _image_service_render_block( $products_menu , $products_menu->title );
	}

	//Main Menu
	$menu_block = block_load('system', 'main-menu');
	$variables['menu-main'] = _image_service_render_block( $menu_block , $menu_block->title );

	//User Menu
	$user_menu_block = block_load('system', 'user-menu'); 
	$variables['menu-user'] = _image_service_render_block($user_menu_block , $user_menu_block->title );

	//Products Sub Menu
	$products_menu_block = block_load('superfish', '1');   
	$variables['products-submenu'] = _image_service_render_block($products_menu_block , $products_menu_block->title );


	//Info Menu
	$info_menu_block = block_load('superfish', '7');      
	$variables['menu-info'] = _image_service_render_block($info_menu_block, $info_menu_block->title );

	
	//FRONT PAGE
	if($variables['is_front']){
		
		if(empty($variables['featured_product'])){
			$featured_product_block = block_load('views' , 'featured_product-block');
			$variables['featured_product'] = _image_service_render_block($featured_product_block , '<none>');
		}

		if(empty($variables['frontpage_news'])){
			$variables['frontpage_news'] = _image_service_render_block( block_load('views', 'frontpage_news-block'), '<none>' );
		}

		if(empty($variables['frontpage_products'])){
			$frontpage_products_block = block_load('views', 'product-block');      
			$variables['frontpage_products'] = _image_service_render_block($frontpage_products_block , '<none>');
		}

		if(empty($variables['view_more_products'])){
			$variables['view_more_products'] = _image_service_render_block( block_load('views', 'product-view_more_products') , '<none>');
		}
	}
	
	//THEME SUGGESTIONS
	if(isset($variables['page']['content']['system_main']['no_content']))
	{
		$variables['page']['content']['system_main']['no_content']['#markup'] = '';
	}

	if(isset($variables['page']['content']['system_main']['nodes']))
	{
		//dsm($variables);
		//unset($variables['page']['content']['system_main']['nodes']);
	}	

	if( isset($variables['node']->type) && $variables['node']->type == 'product' )
	{
		$variables['theme_hook_suggestions'][] = 'page__node_product';
	}

	if( isset($variables['node']->type) && $variables['node']->type == 'news' )
	{
		$variables['theme_hook_suggestions'][] = 'page__node_news';
	}	
	
	if(isset($variables['page']['content']['system_main']['term_heading']['term'])){
		$term = $variables['page']['content']['system_main']['term_heading']['term'];
		
		// Supplier page
		if($term['#bundle'] == 'suppliers'){
			$variables['theme_hook_suggestions'] = array('page__suppliers');
		}
	}
	
}

function _image_service_render_block($block , $title)
{
	if(isset($title)){
		$block->title = $title;
	}
	
	$build = _block_get_renderable_array(_block_render_blocks(array($block)));
	$render = drupal_render($build);
	return $render;
}