<?php

// define('FILES' , '/Users/patrick/Sites/imageservice/sites/default/files' );

// function image_service_init()
// {

// }

// function image_service_preprocess_page(&$variables)
// {
// 	$dots = array('.', '..');

// 	if(file_exists(FILES)){

// 		$files = scandir(FILES);

// 		foreach ( $files as $key => $value) {
// 			if(! in_array( $value, $dots)){
// 				$current_path = FILES.'/'.$value;

// 				if(is_dir($current_path)){
// 					_image_service_check_directory($current_path , $dots );
// 				}
// 			}
// 		}
// 	}	
// }

// function _image_service_check_directory($path , $dots )
// {
// 	$files = scandir($path);

// 	if(!empty($files)){

// 		$match = preg_match( '/.php/', $files );

// 		dsm($match , '_image_service_check_directory' );

// 		foreach ( $files as $key => $value) {

// 			if( !in_array( $value, $dots) ){

// 				$current_path = FILES.'/'.$value;

// 				if(is_dir($current_path)){
// 					_image_service_check_directory($current_path , $dots );
// 				}
// 			}
// 		}
// 	}
// }