<?php

// Fixes the translation problem in Views Exposed Form
function image_service_form_alter(&$form, &$form_state, $form_id)
{
	global $language;
	
	// Only do this if the page is not in English
	if($language->language != 'en'){
		if($form_id == 'views_exposed_form'){
			foreach( $form['field_country_tid']['#options'] as $key=>$value){
				if($key != 'All'){
					$term = taxonomy_term_load($key);
					if (module_exists('i18n_taxonomy')) {
					    module_load_include('inc', 'i18n', 'i18n_taxonomy.pages');
					    $term = i18n_taxonomy_localize_terms($term);
						$form['field_country_tid']['#options'][$key] = $term->name;
					}
				}
			}
		}
	}
}

function image_service_preprocess_page(&$variables)
{
	// SITEWIDE
	if(empty($variables['catchphrases']))
	{
		$catchphrases = views_embed_view('catchphrases');
		$variables['catchphrases'] = $catchphrases;
	}
	
	if(empty($variables['grapepickers'])){
		$grapepickers = views_embed_view('illustrations') ;
		$variables['grapepickers'] = $grapepickers;
	}
	
	//Search form
	if(empty($variables['search_box'])){
		$search_box = drupal_get_form('search_form');
		$variables['search_box'] = drupal_render($search_box);
	}

	//Suppliers Menu
	if(empty($variables['suppliers-menu'])){
		$suppliers_block = block_load('menu', 'menu-suppliers');
		$suppliers_build =  _block_get_renderable_array(_block_render_blocks(array($suppliers_block)));
		$variables['suppliers-menu'] = drupal_render($suppliers_build);
	}

	//Countries Menu
	if(empty($variables['countries-menu'])){
		$countries_block = block_load('menu', 'menu-countries'); 
		$countries_build = _block_get_renderable_array(_block_render_blocks(array($countries_block)));     
		$variables['countries-menu'] = drupal_render($countries_build);
	}

	//Products Menu
	if(empty($variables['products-menu'])){
		$products_block = block_load('menu', 'menu-products'); 
		$products_build = _block_get_renderable_array(_block_render_blocks(array($products_block)));     
		$variables['products-menu'] = drupal_render($products_build);
	}

	//Main Menu
	$main_menu_block = block_load('system', 'main-menu');      
	$variables['menu-main'] = drupal_render(_block_get_renderable_array(_block_render_blocks(array($main_menu_block)))); 

	//User Menu
	$user_menu_block = block_load('system', 'user-menu');      
	$variables['menu-user'] = drupal_render(_block_get_renderable_array(_block_render_blocks(array($user_menu_block)))); 

	//Products Sub Menu
	$products_menu_block = block_load('superfish', '1');      
	$variables['products-submenu'] = drupal_render(_block_get_renderable_array(_block_render_blocks(array($products_menu_block)))); 


	//Info Menu
	$info_menu_block = block_load('superfish', '7');      
	$variables['menu-info'] = drupal_render(_block_get_renderable_array(_block_render_blocks(array($info_menu_block))));

	
	//FRONT PAGE
	if($variables['is_front']){
		
		if(empty($variables['featured_product'])){
			$featured_product = views_embed_view('featured_product') ;
			$variables['featured_product'] = $featured_product;
		}

		if(empty($variables['frontpage_news'])){
			$frontpage_news = views_embed_view('frontpage_news') ;
			$variables['frontpage_news'] = $frontpage_news;
		}

		if(empty($variables['frontpage_products'])){
			$frontpage_products_block = block_load('views', 'product-block');      
			$frontpage_products_build = _block_get_renderable_array(_block_render_blocks(array($frontpage_products_block)));
			$variables['frontpage_products'] = drupal_render($frontpage_products_build);
		}

		if(empty($variables['view_more_products'])){
			$variables['view_more_products'] = views_embed_view('product', 'view_more_products') ;
		}
	}
}